"""empty message

Revision ID: 9c9ca50d73fb
Revises: 6c7c84e03e05
Create Date: 2025-08-23 15:05:42.627980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c9ca50d73fb'
down_revision = '6c7c84e03e05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_price', sa.Numeric(precision=10, scale=2), nullable=False))

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_column('status')
        batch_op.drop_column('start_date')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('money', sa.Numeric(precision=10, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('money')

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_date', sa.DATE(), nullable=False))
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=20), nullable=False))

    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_column('service_price')

    # ### end Alembic commands ###
